{
  "stats": {
    "suites": 1,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2024-03-26T10:34:51.608Z",
    "end": "2024-03-26T10:35:00.746Z",
    "duration": 9138,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "d30dfeb8-45a8-4966-85ed-1f33f34a4b8d",
      "title": "",
      "fullFile": "cypress\\integration\\examples\\BookFlightTest.js",
      "file": "cypress\\integration\\examples\\BookFlightTest.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [],
      "suites": [
        {
          "uuid": "c3762f2b-c02a-4858-bd45-648a9fcc2907",
          "title": "My flight",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
            {
              "title": "Book flight",
              "fullTitle": "My flight Book flight",
              "timedOut": null,
              "duration": 1989,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "cy.visit('https://rahulshettyacademy.com/dropdownsPractise/');",
              "err": {
                "message": "ReferenceError: The following error originated from your application code, not from Cypress.\n\n  > Sys is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "ReferenceError: The following error originated from your application code, not from Cypress.\n\n  > Sys is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at <unknown> (https://rahulshettyacademy.com/dropdownsPractise/:569:1)",
                "diff": null
              },
              "uuid": "8cbcc69c-0346-4992-93a8-644f20a9ba65",
              "parentUUID": "c3762f2b-c02a-4858-bd45-648a9fcc2907",
              "isHook": false,
              "skipped": false
            }
          ],
          "suites": [],
          "passes": [],
          "failures": [
            "8cbcc69c-0346-4992-93a8-644f20a9ba65"
          ],
          "pending": [],
          "skipped": [],
          "duration": 1989,
          "root": false,
          "rootEmpty": false,
          "_timeout": 2000
        }
      ],
      "passes": [],
      "failures": [],
      "pending": [],
      "skipped": [],
      "duration": 0,
      "root": true,
      "rootEmpty": true,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": true,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "7.1.3"
    },
    "marge": {
      "options": {
        "reportDir": "cypress/reports",
        "overwrite": false,
        "html": true,
        "json": true
      },
      "version": "6.2.0"
    }
  }
}